server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
      routes:
        - id: hospital-service
          uri: http://localhost:9001/
          predicates:
            - Path=/hospital-service/**

        - id: hospital-service
          uri: http://localhost:9001/
          predicates:
            - Path=/hospital-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/hospital-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: http://localhost:9002/
          predicates:
            - Path=/user-service/**
            -
        - id: hospital-service
          uri: http://localhost:9001/
          predicates:
            - Path=/hospital-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/hospital-service/(?<segment>.*), /$\{segment}

        - id: emergency-service
          uri: http://localhost:9003/
          predicates:
            - Path=/emergency-service/**

        - id: reservation-service
          uri: http://localhost:9004/
          predicates:
            - Path=/reservation-service/**
        
        - id: mypage-service
          uri: http://localhost:9005/
          predicates:
            - Path=/mypage-service/**
            
management: # 모니터링
  endpoints:
    web:
      base-path: /apigateway-service/actuator
      exposure:
        include: refresh, beans, httptrace, health, info, metrics, prometheus  # 노출할 Actuator 엔드포인트 목록
  endpoint:
    health:
      show-details: always  # 모든 세부사항을 항상 표시
  prometheus:
    metrics:
      export:
        enabled: true



